name: dart_cmd_bot
description: Telegram bot for remote maintenance of your working computer.
version: 0.0.1
# repository: https://github.com/Bachar-official/dart_cmd_bot

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  charset: ^2.0.1
  teledart: ^0.6.1
  win32: ^5.2.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
